export const API = {
  REGISTER: '/user/register',
  LOGIN: '/user/login',
  GET_TYPES: '/types',
  GET_TAGS: '/tags',
  ADD_CAPSTONE: '/capstone/add',
  UPDATE_CAPSTONE: '/capstone/update',
  GET_CAPSTONES: '/capstone/list',
  GET_ASSIGNED: '/capstone/assigned/',
  GET_OWNED: '/capstone/owned/',
  UPDATE_RATING: '/capstone/update/rating',
  UPDATE_PERCENTAGE: '/capstone/update/percentage',
  UPDATE_VIEWS: '/capstone/update/views',
  ADD_COMMENT: '/capstone/add/comment',
  GET_COMMENTS: '/capstone/comments/',
  GET_CAPSTONE: '/capstone/list/',
  GET_PROFESSORS: '/professors',
  UPLOAD_DOCUMENT: '/capstone/upload_document',
  UPDATE_USER: '/user/update',
};
